### ISSUE TITLE
Information about Home Manager

### ISSUE THREAD

**Issue by gfsd3v** [XNM1/linux-nixos-hyprland-config-dotfiles#1]
First of all thanks for the awesome repo, I'm using a lot of things from it.

I just was wondering why u decided to not use Home Manager and copy and past the home config files manually,  did u found any issues or blockers with Home Manager?

Thanks for the incredible help :+1:

**Comment by XNM1** [comment]
Thank you for using my repo. It's really nice to know that I've been able to help someone. 🤍

To be honest, there are no specific dealbreakers for me; perhaps all my configurations from the `.config` directory can be represented through the Home Manager configuration. Home Manager supports a wide range of configuration options (see [here](https://nix-community.github.io/home-manager/options.html)), and if there's an application that isn't directly supported, you can use the `home.file` option for such cases.

However, there were some reasons why I chose to configure my programs separately and manually:

- **Flexibility**: I wasn't entirely sure if I could represent all my configurations through Home Manager, given that I use a variety of software and often experiment with cutting-edge tools. To avoid potential future problems and incompatibilities, I decided not to rely on Home Manager.

- **Consistency**: I made a conscious decision to clearly separate system configurations from application configurations. I attempted to encapsulate all my system configurations in Nix config files, while keeping my application configurations in their native formats within the `.config` directory. I wanted to avoid a situation where some configurations are in Nix format (and applies through Home Manager) and others are in their native formats.

- **Efficiency**: It was quicker and easier for me to work with native file formats for applications. This approach allowed me to reference official documentation, guides, or use default generated configs without the need to transform configurations into Nix format, which can be time-consuming.

Thank you once again for using my repository. I hope this answer addresses your question and assists you with your own configurations. Have a great day! 😊

**Comment by gfsd3v** [comment]
Gotcha, thx for the very detailed response mate, it makes total sense 🫡

**Comment by XNM1** [comment]
You're very welcome! 🌟😊
