### ISSUE TITLE
flake issue

### ISSUE THREAD

**Issue by blurskye** [XNM1/linux-nixos-hyprland-config-dotfiles#4]
`sudo nixos-rebuild switch --flake /etc/nixos`
gives

```
error: flake 'path:/etc/nixos' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."nixos".config.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations."nixos".config.system.build.nixos-rebuild' or 'nixosConfigurations."nixos".config.system.build.nixos-rebuild'
```
i have done all the steps mentioned in readme, and i do have flakes and nix-command enabled, still i get this error, has some nix syntax been updated?

i copied 
`linux-nixos-hyprland-config-dotfiles/nixos/*` to `/etc/nixos/` (hardware config is still the previous one) and tried rebuilding

**Comment by blurskye** [comment]
@XNM1 help, am i missing something

**Comment by XNM1** [comment]
Hi, sorry for the delayed response.

I'm not sure what's causing the problem.

Please try one of the following:

1. Navigate to `/etc/nixos` using the `cd` command and run:
   ```bash
   sudo nixos-rebuild switch --flake .#
   ```
2. Or, if your machine is named 'isitreal-laptop' (change it to your machine name if not),  run:
   ```bash
   sudo nixos-rebuild switch --flake .#isitreal-laptop
   ```
3. If you're using my system completely, run the following command in the fish shell:
   ```bash
   nswitchu
   ```

Let me know if this resolves the issue. Have a great day! I'll continue investigating this problem.

**Comment by blurskye** [comment]
sorry for getting back to you late, it still gives me that error
![image](https://github.com/XNM1/linux-nixos-hyprland-config-dotfiles/assets/145671529/0b647639-1e28-4a11-baf1-9a4247048a8f)

**Comment by blurskye** [comment]
![image](https://github.com/XNM1/linux-nixos-hyprland-config-dotfiles/assets/145671529/d7cfc040-bdb8-46ae-9548-842b4318f6a9)
nix flakes are enabled, just to be sure i checked the nix.conf file

**Comment by XNM1** [comment]
Hi, I see. Could you please share the contents of your current `flake.nix` in `/etc/nixos` with me?

**Comment by blurskye** [comment]
@XNM1 here it is

```nix
{
  description = "XNM's NixOS Configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    rust-overlay.url = "github:oxalica/rust-overlay";
  };

  outputs = { nixpkgs, ... } @ inputs:
    {
      nixosConfigurations.master256 = nixpkgs.lib.nixosSystem {
        specialArgs = { inherit inputs; };
        modules = [
          ./configuration.nix
          ./hardware-configuration.nix
          # ./fingerprint-scanner.nix
          ./sound.nix
          ./usb.nix
          ./time.nix
          ./swap.nix
          ./bootloader.nix
          ./nix-settings.nix
          ./nixpkgs.nix
          ./gc.nix
          ./auto-upgrade.nix
          ./linux-kernel.nix
          ./screen.nix
          ./display-manager.nix
          ./theme.nix
          ./internationalisation.nix
          ./fonts.nix
          ./security-services.nix
          ./services.nix
          # ./printing.nix
          # ./gnome.nix
          ./hyprland.nix
          ./environment-variables.nix
          ./bluetooth.nix
          ./networking.nix
          # ./mac-randomize.nix
          # ./open-ssh.nix
          ./firewall.nix
          ./dns.nix
          # ./vpn.nix
          ./users.nix
          ./virtualisation.nix
          ./programming-languages.nix
          ./lsp.nix
          ./rust.nix
          ./wasm.nix
          ./info-fetchers.nix
          ./utils.nix
          ./terminal-utils.nix
        ];
      };
    };
}```

**Comment by XNM1** [comment]
Thank you for providing the `flake.nix` content.

Please try running the following command:

```bash
sudo nixos-rebuild switch --flake /etc/nixos#master256
```

If you have used a different name in place of `master256`, make sure to substitute that name in the command. For example, if your configuration is defined as follows:

```nix
outputs = { nixpkgs, ... } @ inputs:
    {
      nixosConfigurations.some-name = nixpkgs.lib.nixosSystem {
        specialArgs = { inherit inputs; };
        modules = [
```

Then the corresponding command would be:

```bash
sudo nixos-rebuild switch --flake /etc/nixos#some-name
```

In my case, it is `isitreal-laptop`, so the command for me looks like:

```bash
sudo nixos-rebuild switch --flake /etc/nixos#isitreal-laptop
```

However, in practice, I simply use:

```bash
sudo nixos-rebuild switch --flake /etc/nixos
```

This command works fine for me. I will check for any updates in NixOS, maybe something was changed, and update my README.

Let me know if this resolves the issue, and have a great day! :)

**Comment by XNM1** [comment]
I also have another suggestion. You can try changing the `master256` hostname to your preferred name. If it's already your preferred hostname, you can leave it unchanged. Additionally, remember to update the hostname in the network configuration file `networking.nix` under the `networking.hostName = "your-host-name"` section.

After making these changes, execute the following command: 

```bash
sudo nixos-rebuild switch --flake /etc/nixos#your-host-name
```

Subsequently, try running a simplified version of the previous command:

```bash
sudo nixos-rebuild switch --flake /etc/nixos
```

Check to see if it works as intended.

**Comment by blurskye** [comment]
thanks, i got that part, well now i get another error, 
```
building the system configuration...
Directory "/boot/efi" is not the root of the file system.
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
Traceback (most recent call last):
  File "/nix/store/78zv5q6z80kir5r2r09sim5dq45lnj4a-systemd-boot", line 344, in <module>
    main()
  File "/nix/store/78zv5q6z80kir5r2r09sim5dq45lnj4a-systemd-boot", line 332, in main
    install_bootloader(args)
  File "/nix/store/78zv5q6z80kir5r2r09sim5dq45lnj4a-systemd-boot", line 270, in install_bootloader
    raise Exception("could not find any previously installed systemd-boot")
Exception: could not find any previously installed systemd-boot
warning: error(s) occurred while switching to the new configuration
```
(systemd was installed in the pc, idk what `could not find any previously installed systemd-boot` even means)
![image](https://github.com/XNM1/linux-nixos-hyprland-config-dotfiles/assets/145671529/2ccd8d8c-25ab-4950-97a0-d81e74fec7df)

**Comment by blurskye** [comment]
alright figured it out, i think you should set boot root to be /boot because most people installed it from calamares ig, or have a it noted in readme, 

points of confusion, 

`sudo nixos-rebuild switch --flake /etc/nixos#your-host-name` thing
and
bootloader root thing
 thank you for the config
 :>
