### ISSUE TITLE
Policy Authentication Agent?

### ISSUE THREAD

**Issue by trm109** [XNM1/linux-nixos-hyprland-config-dotfiles#6]
For personal reference, where is the policy authentication agent config located in the nix config? I don't seem to see one executed by the hyprland.conf file either.

Thanks in advance.

**Comment by XNM1** [comment]
Hi, If you're referring to something like `polkit`, I don't use it. As far as I know, this type of software is employed in complex desktop environments and certain graphical applications that require authorization or administrative privileges. It's often used for setting up granular permissions.

I primarily operate in the terminal, and for my needs, a straightforward `sudo` is secure and sufficient. Regarding user groups, I manually add them to users in the `nixos/users.nix` file under the `extraGroups` section.

If you are interested in enabling the Authentication Agent, you can uncomment the `security.polkit.enable = true;` section in the `nixos/security-services.nix` config file. Additionally, you can add a `security.polkit.extraConfig` section with your specified configuration. Alternatively, you can enable another Authentication Agent following the NixOS guidelines.

**Comment by trm109** [comment]
Thanks for the info, I'm considering whether or not I actually need a polkit for my configuration now, never considered it before.

This configuration is great, a lot of foreign stuff to learn about!

**Comment by artemplummy** [comment]
Thank you; it truly means a lot to me. Initially, I also was uncertain about the necessity of `polkit` (or a similar tools). However, after conducting thorough research, I have come to the conclusion that it is not essential for my workflow and system.

Having been a teacher in the past, I consistently encouraged individuals to explore and experiment on their own. What may good fit to me might not be suitable for others.

I hope you find the best solution for your needs

**Comment by XNM1** [comment]
Thank you; it truly means a lot to me. Initially, I also was uncertain about the necessity of `polkit` (or a similar tools). However, after conducting thorough research, I have come to the conclusion that it is not essential for my workflow and system.

Having been a teacher in the past, I consistently encouraged individuals to explore and experiment on their own. What may good fit to me might not be suitable for others.

I hope you find the best solution for your needs
